//
// Generated file, do not edit! Created by nedtool 5.5 from msg/StreamingMessage.msg.
//

#ifndef __ECSNETPP_STREAMINGMESSAGE_M_H
#define __ECSNETPP_STREAMINGMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace ecsnetpp {

// cplusplus {{
#include "omnetpp.h"
// }}

/**
 * Class generated from <tt>msg/StreamingMessage.msg:32</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet StreamingMessage
 * {
 *     int messageId;
 *     string sender;
 *     //	int size;
 *     string content;
 *     bool isProcessingDelayInCyclesPerEvent;
 *     //	double cyclesPerEvent;
 *     double processingDelayPerEvent;
 *     double selectivityRatio;
 *     simtime_t startTime;
 *     simtime_t operatorIngressTime;
 *     simtime_t channelIngressTime;
 *     double networkDelay;
 *     double processingDelay;
 *     double edgeProcessingDelay;
 * 
 *     // Per-hop telemetry (max 8 hops)
 *     int numHops = 0;
 *     bool pendingHopStamp = false;  // set true by supervisor after link stamp; cleared by CPUCore after proc stamp
 *     double hopLinkMs[8];           // WAN link delay to reach each hop (ms)
 *     double hopProcMs[8];           // CPU processing delay at each hop destination (ms)
 *     int hopQueueDepth[8];          // CPUCore queue depth when message was processed at each hop
 *     string hopNodeLabel[8];        // "category\@nodeName" stamped by CPUCore at each hop
 * 
 *     // Source identity — set once at creation, never overwritten
 *     string sourceLabel = "";       // "category\@nodeName" of the generating source task
 * }
 * </pre>
 */
class StreamingMessage : public ::omnetpp::cPacket
{
  protected:
    int messageId;
    ::omnetpp::opp_string sender;
    ::omnetpp::opp_string content;
    bool isProcessingDelayInCyclesPerEvent;
    double processingDelayPerEvent;
    double selectivityRatio;
    ::omnetpp::simtime_t startTime;
    ::omnetpp::simtime_t operatorIngressTime;
    ::omnetpp::simtime_t channelIngressTime;
    double networkDelay;
    double processingDelay;
    double edgeProcessingDelay;
    int numHops;
    bool pendingHopStamp;
    double hopLinkMs[8];
    double hopProcMs[8];
    int hopQueueDepth[8];
    ::omnetpp::opp_string hopNodeLabel[8];
    ::omnetpp::opp_string sourceLabel;

  private:
    void copy(const StreamingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StreamingMessage&);

  public:
    StreamingMessage(const char *name=nullptr, short kind=0);
    StreamingMessage(const StreamingMessage& other);
    virtual ~StreamingMessage();
    StreamingMessage& operator=(const StreamingMessage& other);
    virtual StreamingMessage *dup() const override {return new StreamingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);
    virtual const char * getSender() const;
    virtual void setSender(const char * sender);
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
    virtual bool getIsProcessingDelayInCyclesPerEvent() const;
    virtual void setIsProcessingDelayInCyclesPerEvent(bool isProcessingDelayInCyclesPerEvent);
    virtual double getProcessingDelayPerEvent() const;
    virtual void setProcessingDelayPerEvent(double processingDelayPerEvent);
    virtual double getSelectivityRatio() const;
    virtual void setSelectivityRatio(double selectivityRatio);
    virtual ::omnetpp::simtime_t getStartTime() const;
    virtual void setStartTime(::omnetpp::simtime_t startTime);
    virtual ::omnetpp::simtime_t getOperatorIngressTime() const;
    virtual void setOperatorIngressTime(::omnetpp::simtime_t operatorIngressTime);
    virtual ::omnetpp::simtime_t getChannelIngressTime() const;
    virtual void setChannelIngressTime(::omnetpp::simtime_t channelIngressTime);
    virtual double getNetworkDelay() const;
    virtual void setNetworkDelay(double networkDelay);
    virtual double getProcessingDelay() const;
    virtual void setProcessingDelay(double processingDelay);
    virtual double getEdgeProcessingDelay() const;
    virtual void setEdgeProcessingDelay(double edgeProcessingDelay);
    virtual int getNumHops() const;
    virtual void setNumHops(int numHops);
    virtual bool getPendingHopStamp() const;
    virtual void setPendingHopStamp(bool pendingHopStamp);
    virtual unsigned int getHopLinkMsArraySize() const;
    virtual double getHopLinkMs(unsigned int k) const;
    virtual void setHopLinkMs(unsigned int k, double hopLinkMs);
    virtual unsigned int getHopProcMsArraySize() const;
    virtual double getHopProcMs(unsigned int k) const;
    virtual void setHopProcMs(unsigned int k, double hopProcMs);
    virtual unsigned int getHopQueueDepthArraySize() const;
    virtual int getHopQueueDepth(unsigned int k) const;
    virtual void setHopQueueDepth(unsigned int k, int hopQueueDepth);
    virtual unsigned int getHopNodeLabelArraySize() const;
    virtual const char * getHopNodeLabel(unsigned int k) const;
    virtual void setHopNodeLabel(unsigned int k, const char * hopNodeLabel);
    virtual const char * getSourceLabel() const;
    virtual void setSourceLabel(const char * sourceLabel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StreamingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StreamingMessage& obj) {obj.parsimUnpack(b);}

} // namespace ecsnetpp

#endif // ifndef __ECSNETPP_STREAMINGMESSAGE_M_H

